<?php
return [
  "Afghanistan"=> [
    "Badakhshan",
    "Badghis",
    "Baghlan",
    "Balkh",
    "Bamyan",
    "Daikondi",
    "Farah",
    "Faryab",
    "Ghazni",
    "Ghor",
    "Helmand",
    "Herat",
    "Jowzjan",
    "Kabul",
    "Kandahar",
    "Kapisa",
    "Khost",
    "Kunar",
    "Kunduz",
    "Laghman",
    "Logar",
    "Nangarhar",
    "Nimruz",
    "Nuristan",
    "Oruzgan",
    "Paktia",
    "Paktika",
    "Panjshir",
    "Parwan",
    "Samangan",
    "Sar-e Pol",
    "Takhar",
    "Urozgan",
    "Zabul"
  ],
  "Afrique du Sud"=> [
    "Cap-Nord",
    "Cap-Occidental",
    "Cap-Oriental",
    "Gauteng",
    "Kwazulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "Nord du Cap",
    "Nord-Ouest"
  ],
  "Albanie"=> [
    "Berat",
    "Bulqizë",
    "Devoll",
    "Dibër",
    "Durrës",
    "Elbasan",
    "Fier",
    "Gjirokastër",
    "Gramsh",
    "Has",
    "Kavajë",
    "Kolçë",
    "Korçë",
    "Krujë",
    "Kukës",
    "Kurbin",
    "Kuçovë",
    "Lezhë",
    "Librazhd",
    "Lushnjë",
    "Mallakastër",
    "Malësi e Madhe",
    "Mat",
    "Mirditë",
    "Peqin",
    "Pogradec",
    "Pukë",
    "Përmet",
    "Qarku i Beratit",
    "Qarku i Dibrës",
    "Qarku i Durrësit",
    "Qarku i Elbasanit",
    "Qarku i Fierit",
    "Qarku i Gjirokastrës",
    "Qarku i Korçës",
    "Qarku i Kukësit",
    "Qarku i Lezhës",
    "Qarku i Shkodrës",
    "Qarku i Tiranës",
    "Qarku i Vlorës",
    "Rrogozhinë",
    "Sarandë",
    "Selenicë",
    "Shkodër",
    "Skrapar",
    "Tepelenë",
    "Tirana",
    "Tropojë",
    "Vlorë"
  ],
  "Algérie"=> [
    "Adrar",
    "Alger",
    "Annaba",
    "Aïn Defla",
    "Aïn Témouchent",
    "Batna",
    "Biskra",
    "Blida",
    "Bordj Bou Arréridj",
    "Bouira",
    "Boumerdès",
    "Béchar",
    "Béjaïa",
    "Chlef",
    "Constantine",
    "Djelfa",
    "El Bayadh",
    "El Oued",
    "El Tarf",
    "Ghardaïa",
    "Guelma",
    "Illizi",
    "Jijel",
    "Khenchela",
    "Laghouat",
    "M'Sila",
    "Mascara",
    "Mila",
    "Mostaganem",
    "Médéa",
    "Naâma",
    "Oran",
    "Ouargla",
    "Oum El Bouaghi",
    "Relizane",
    "Saïda",
    "Sidi Bel Abbès",
    "Skikda",
    "Souk Ahras",
    "Sétif",
    "Tamanrasset",
    "Tiaret",
    "Tindouf",
    "Tipasa",
    "Tissemsilt",
    "Tizi Ouzou",
    "Tlemcen",
    "Tébessa"
  ],
  "Allemagne"=> [
    "Bade-Wurtemberg",
    "Basse-Saxe",
    "Bavière",
    "Berlin",
    "Brandebourg",
    "Bremen",
    "Hambourg",
    "Hesse",
    "Mecklembourg-Pomeranie-Occidentale",
    "Rhénanie-du-Nord-Westphalie",
    "Rhénanie-Palatinat",
    "Saarland",
    "Saxe",
    "Saxe-Anhalt",
    "Schleswig-Holstein",
    "Thuringe"
  ],
  "Andorre"=> [],
  "Angola"=> [
    "Bengo",
    "Benguela",
    "Bie",
    "Cabinda",
    "Cuando Cubango",
    "Cuanza Norte",
    "Cuanza Sul",
    "Cunene",
    "Huambo",
    "Huila",
    "Luanda",
    "Lunda Norte",
    "Lunda Sul",
    "Malanje",
    "Moxico",
    "Namibe",
    "Quand-Cubango",
    "Uige",
    "Zaire"
  ],
  "Antigua-et-Barbuda"=> [
    "Saint-Georges",
    "Saint-Jean",
    "Saint-Paul",
    "Saint-Philippe",
    "Saint-Pierre",
    "Sainte-Marie"
  ],
  "Arabie saoudite"=> [
    "Al-Bahah",
    "Al-Jawf",
    "Al-Madinah",
    "Asir",
    "Ha'il",
    "Jazan",
    "La Mecque",
    "Médine",
    "Najran",
    "Province orientale",
    "Qassim",
    "Riyad",
    "Tabuk"
  ],
  "Argentine"=> [
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Corrientes",
    "Córdoba",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán",
    "Ville de Buenos Aires"
  ],
  "Arménie"=> [
    "Aragatsotn",
    "Ararat",
    "Armavir",
    "Gegarkunik",
    "Kotayk",
    "Lori",
    "Shirak",
    "Syunik",
    "Tavush",
    "Vayots Dzor",
    "Yerevan"
  ],
  "Australie"=> [
    "Australie-Méridionale",
    "Australie-Occidentale",
    "Nouvelle-Galles du Sud",
    "Queensland",
    "Tasmanie",
    "Territoire de la capitale australienne",
    "Territoire du Nord",
    "Victoria"
  ],
  "Autriche"=> [
    "Basse-Autriche",
    "Burgenland",
    "Carinthie",
    "Haute-Autriche",
    "Styrie",
    "Tyrol",
    "Vienne",
    "Vorarlberg"
  ],
  "Azerbaïdjan"=> [
    "Absheron",
    "Agdash",
    "Aghdam",
    "Aghjabadi",
    "Aghraer",
    "Agshalta",
    "Agstafa",
    "Akhmeta",
    "Astara",
    "Babek",
    "Baku",
    "Balakan",
    "Barda",
    "Beylagan",
    "Bilasuvar",
    "Dashkasan",
    "Fuzuli",
    "Gadabay",
    "Goranboy",
    "Goychay",
    "Goygol",
    "Hajigabul",
    "Imishli",
    "Ismailli",
    "Jabrayil",
    "Jalilabad",
    "Julfa",
    "Kangarli",
    "Khachmaz",
    "Khankandi",
    "Khizi",
    "Khoblar",
    "Khojavend",
    "Lerik",
    "Masalli",
    "Neftchala",
    "Oguz",
    "Ordubad",
    "Oussou",
    "Qabala",
    "Qakh",
    "Qazakh",
    "Qobustan",
    "Quba",
    "Qubadli",
    "Qusar",
    "Saatly",
    "Sabirabad",
    "Sakhour",
    "Salyan",
    "Samukh",
    "Shabiyar",
    "Shahbuz",
    "Shakhtakhti",
    "Sharour",
    "Sheki",
    "Shemakha",
    "Shusha",
    "Siazan",
    "Siyazan",
    "Tartar",
    "Tovuz",
    "Ujar",
    "Yardimli",
    "Yevlakh",
    "Zagatala",
    "Zangilan",
    "Zaqatala"
  ],
  "Bahamas"=> [
    "Abaco",
    "Acklins",
    "Andros",
    "Berry Islands",
    "Bimini",
    "Cat Island",
    "Crooked Island",
    "Exuma",
    "Grand Bahama",
    "Harbour Island",
    "Inagua",
    "Long Island",
    "Mayaguana",
    "New Providence",
    "Ragged Island",
    "Rum Cay",
    "San Salvador"
  ],
  "Bahreïn"=> [
    "Gouvernorat du Muharraq",
    "Gouvernorat du Nord",
    "Gouvernorat du Sud",
    "Manama"
  ],
  "Bangladesh"=> [
    "Division de Barisal",
    "Division de Chittagong",
    "Division de Dacca",
    "Division de Khulna",
    "Division de Mymensingh",
    "Division de Rajshahi",
    "Division de Rangpur",
    "Division de Sylhet"
  ],
  "Barbade"=> [
    "Christ Church",
    "Saint Andrew",
    "Saint George",
    "Saint James",
    "Saint John",
    "Saint Joseph",
    "Saint Lucy",
    "Saint Michael",
    "Saint Peter",
    "Saint Philip",
    "Saint Thomas"
  ],
  "Belgique"=> [
    "Anvers",
    "Brabant flamand",
    "Brabant wallon",
    "Bruxelles-Capitale",
    "Flandre-Occidentale",
    "Flandre-Orientale",
    "Hainaut",
    "Limbourg",
    "Liège",
    "Luxembourg",
    "Namur"
  ],
  "Belize"=> [
    "Belize",
    "Cayo",
    "Corozal",
    "Orange Walk",
    "Stann Creek",
    "Toledo"
  ],
  "Bhoutan"=> [
    "Bumthang",
    "Chhukha",
    "Chirang",
    "Dagana",
    "Gasa",
    "Geylegphug",
    "Ha",
    "Lhuntse",
    "Mongar",
    "Paro",
    "Pemagatshel",
    "Punakha",
    "Samchi",
    "Samdrup Jongkhar",
    "Shemgang",
    "Tashigang",
    "Thimphu",
    "Tongsa",
    "Wangdi Phodrang"
  ],
  "Birmanie (Myanmar)"=> [
    "Bago",
    "Division d'Ayeyarwady",
    "Division de Mandalay",
    "Division de Naypyidaw",
    "Division de Yangon",
    "Rakhine",
    "Sagaing",
    "Tanintharyi",
    "État de Chin",
    "État de Kachin",
    "État de Kayah",
    "État de Kayin",
    "État de Mon",
    "État de Rakhine",
    "État de Shan"
  ],
  "Bolivie"=> [
    "Beni",
    "Chuquisaca",
    "Cochabamba",
    "La Paz",
    "Oruro",
    "Pando",
    "Potosí",
    "Santa Cruz",
    "Tarija"
  ],
  "Bosnie-Herzégovine"=> [
    "Bréko",
    "Canton d'Una-Sana",
    "Canton de Basse-Bosnie",
    "Canton de Bréko",
    "Canton de Gorazde",
    "Canton de Gornji Vakuf-Uskoplje",
    "Canton de l'Ouest-Bosnie",
    "Canton de l'Ouest-Herzégovine",
    "Canton de Livno",
    "Canton de Sarajevo",
    "Canton de Tuzla",
    "Canton du Centre",
    "Canton du Haut-Drin",
    "Canton Posavina",
    "Canton Zenica-Doboj",
    "Entité de Republika Srpska"
  ],
  "Botswana"=> [
    "Central",
    "Ghanzi",
    "Kgalagadi",
    "Kgatleng",
    "Kweneng",
    "Nord-Est",
    "Nord-Ouest",
    "Sud",
    "Sud-Est",
    "Ville de Gaborone",
    "Ville de Lobatse"
  ],
  "Brunei"=> [
    "Belait",
    "Brunei-Muara",
    "Temburong",
    "Tutong"
  ],
  "Brésil"=> [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Paraná",
    "Paraíba",
    "Pará",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "Sergipe",
    "São Paulo",
    "Tocantins"
  ],
  "Bulgarie"=> [
    "Blagoevgrad",
    "Burgas",
    "Dobrich",
    "Gabrovo",
    "Kardzhali",
    "Kyustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Rousse",
    "Shumen",
    "Silistra",
    "Sliven",
    "Smolyan",
    "Sofia",
    "Stara Zagora",
    "Targovishte",
    "Varna",
    "Veliko Tarnovo",
    "Vidin",
    "Vratsa",
    "Yambol"
  ],
  "Burkina Faso"=> [
    "Boucle du Mouhoun",
    "Cascades",
    "Centre",
    "Centre-Est",
    "Centre-Nord",
    "Centre-Ouest",
    "Centre-Sud",
    "Est",
    "Hauts-Bassins",
    "Nord",
    "Plateau-Central",
    "Sahel",
    "Sud-Ouest"
  ],
  "Burundi"=> [
    "Bubanza",
    "Bujumbura Mairie",
    "Bujumbura Rural",
    "Bururi",
    "Cankuzo",
    "Cibitoke",
    "Gitega",
    "Karuzi",
    "Kayanza",
    "Kirundo",
    "Makamba",
    "Muramvya",
    "Muyinga",
    "Mwaro",
    "Ngozi",
    "Rutana",
    "Ruyigi"
  ],
  "Bélarus"=> [
    "Brest",
    "Gomel",
    "Grodno",
    "Minsk",
    "Mogilev",
    "Ville de Minsk"
  ],
  "Bénin"=> [
    "Alibori",
    "Atacora",
    "Atlantique",
    "Borgou",
    "Collines",
    "Couffo",
    "Donga",
    "Littoral",
    "Mono",
    "Ouémé",
    "Plateau",
    "Zou"
  ],
  "Cambodge"=> [
    "Banteay Meanchey",
    "Battambang",
    "Kampong Cham",
    "Kampong Chhnang",
    "Kampong Speu",
    "Kampong Thom",
    "Kampot",
    "Kandal",
    "Kep",
    "Koh Kong",
    "Kratié",
    "Mondolkiri",
    "Oddar Meanchey",
    "Pailin",
    "Phnom Penh",
    "Preah Vihear",
    "Prey Veng",
    "Pursat",
    "Ratanakiri",
    "Siem Reap",
    "Stung Treng",
    "Svay Rieng",
    "Takeo",
    "Tbong Khmum"
  ],
  "Cameroun"=> [
    "Adamaoua",
    "Centre",
    "Est",
    "Extrême-Nord",
    "Littoral",
    "Nord",
    "Nord-Ouest",
    "Ouest",
    "Sud",
    "Sud-Ouest"
  ],
  "Canada"=> [
    "Alberta",
    "Colombie-Britannique",
    "Manitoba",
    "Nouveau-Brunswick",
    "Nouvelle-Écosse",
    "Nunavut",
    "Ontario",
    "Québec",
    "Saskatchewan",
    "Terre-Neuve-et-Labrador",
    "Territoires du Nord-Ouest",
    "Yukon",
    "Île-du-Prince-Édouard"
  ],
  "Cap-Vert"=> [
    "Boa Vista",
    "Brava",
    "Fogo",
    "Maio",
    "Paul",
    "Ribeira Grande de Santiago",
    "Sal",
    "Santo Antão",
    "São Filipe",
    "São Miguel",
    "São Nicolau",
    "São Vicente",
    "Tarrafal",
    "Tarrafal de São Nicolau"
  ],
  "Chili"=> [
    "Aisén",
    "Antofagasta",
    "Araucanía",
    "Arica et Parinacota",
    "Biobío",
    "Coquimbo",
    "Los Lagos",
    "Los Ríos",
    "Magallanes",
    "Maule",
    "O'Higgins",
    "Région métropolitaine de Santiago",
    "Tarapacá",
    "Valparaíso",
    "Ñuble"
  ],
  "Chine"=> [
    "Anhui",
    "Beijing",
    "Chongqing",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guangxi",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hubei",
    "Hunan",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanghai",
    "Sichuan",
    "Tianjin",
    "Xinjiang",
    "Xizang (Tibet)",
    "Yunnan",
    "Zhejiang"
  ],
  "Chypre"=> [
    "Famagouste",
    "Kyrenia",
    "Larnaka",
    "Limassol",
    "Nicosie",
    "Paphos"
  ],
  "Colombie"=> [
    "Amazonas",
    "Antioquia",
    "Arauca",
    "Archipel de San Andrés, Providencia et Santa Catalina",
    "Atlantico",
    "Bolívar",
    "Boyacá",
    "Caldas",
    "Caquetá",
    "Casanare",
    "Cauca",
    "Cesar",
    "Chocó",
    "Cundinamarca",
    "Córdoba",
    "Guainía",
    "Guaviare",
    "Huila",
    "la capitale de la Colombie",
    "La Guajira",
    "Magdalena",
    "Meta",
    "Nariño",
    "Norte de Santander",
    "Putumayo",
    "Quindío",
    "Risaralda",
    "San Martín",
    "Sucre",
    "Tolima",
    "Valle del Cauca",
    "Vaupés",
    "Vichada"
  ],
  "Comores"=> [
    "Anjouan",
    "Grande Comore",
    "Mohéli"
  ],
  "Congo (Brazzaville)"=> [
    "Bouenza",
    "Brazzaville",
    "Cuvette",
    "Cuvette-Ouest",
    "Kouilou",
    "Likouala",
    "Lékoumou",
    "Niari",
    "Plateaux",
    "Pointe-Noire",
    "Pool",
    "Sangha"
  ],
  "Congo (Kinshasa)"=> [
    "Bandundu",
    "Bas-Congo",
    "Haut-Katanga",
    "Haut-Lomami",
    "Haut-Uele",
    "Ituri",
    "Kasaï",
    "Kasaï-Central",
    "Kasaï-Orientale",
    "Kinshasa",
    "Kwilu",
    "Lomami",
    "Lualaba",
    "Mai-Ndombe",
    "Mongala",
    "Nord-Kivu",
    "Nord-Ubangi",
    "Sankuru",
    "Sud-Kivu",
    "Sud-Ubangi",
    "Tanganyika",
    "Tshopo",
    "Tshuapa",
    "Équateur"
  ],
  "Corée du Nord"=> [
    "Chagang",
    "Hamgyong du Nord",
    "Hamgyong du Sud",
    "Hwanghae du Nord",
    "Hwanghae du Sud",
    "Kangwon",
    "Pyongan du Nord",
    "Pyongan du Sud",
    "Pyongyang",
    "Ryanggang"
  ],
  "Corée du Sud"=> [
    "Chungbuk",
    "Chungnam",
    "Gangwon",
    "Gyeongbuk",
    "Gyeonggi",
    "Gyeongnam",
    "Incheon",
    "Jeju",
    "Jeonbuk",
    "Jeonnam",
    "Seoul",
    "Ulsan"
  ],
  "Costa Rica"=> [
    "Alajuela",
    "Cartago",
    "Guanacaste",
    "Heredia",
    "Limón",
    "Puntarenas",
    "San José"
  ],
  "Croatie"=> [
    "Bjelovar-Bilogora",
    "Brod-Posavina",
    "Comitat d'Istrie",
    "Dubrovnik-Neretva",
    "Karlovac",
    "Koprivnica-Križevci",
    "Krapina-Zagorje",
    "Lika-Senj",
    "Međimurje",
    "Požega-Slavonie",
    "Primorje-Gorski Kotar",
    "Sisak-Moslavina",
    "Split-Dalmatie",
    "Varaždin",
    "Ville de Zagreb",
    "Virovitica-Podravina",
    "Vukovar-Srijem",
    "Zadar",
    "Zagorie",
    "Zagreb",
    "Šibenik-Knin"
  ],
  "Cuba"=> [
    "Artemisa",
    "Camagüey",
    "Ciego de Ávila",
    "Cienfuegos",
    "Granma",
    "Guantánamo",
    "Holguín",
    "Isla de la Juventud",
    "La Habana",
    "Las Tunas",
    "Matanzas",
    "Mayabeque",
    "Pinar del Río",
    "Sancti Spíritus",
    "Santiago de Cuba",
    "Villa Clara"
  ],
  "Côte d'Ivoire"=> [
    "Agneby-Tiassa",
    "Bafing",
    "Bagoué",
    "Bounkari",
    "Bélier",
    "Béré",
    "Cavally",
    "Denguélé",
    "Dix-Huit Montagnes",
    "Fromager",
    "Gboko",
    "Gbêkê",
    "Grimbert",
    "Gôh",
    "Gôh-Djiboua",
    "Hambol",
    "Haut-Sassandra",
    "Iffou",
    "Indénié-Djuablin",
    "Kabadougou",
    "Kasso-Kê",
    "Komoe",
    "Kompienga",
    "Kossou",
    "La Mé",
    "Lacs",
    "Lôh-Djiboua",
    "Marahoué",
    "Maro",
    "Moyen-Cavally",
    "Moyen-Comoé",
    "N'zi-Comoé",
    "Nandé",
    "Nawa",
    "Poro",
    "San-Pédro",
    "Sassandra-Marahoué",
    "Savanes",
    "Sud-Bandama",
    "Tchologo",
    "Tonklé",
    "Woroba",
    "Worodougou",
    "Yamoussoukro",
    "Zanzan"
  ],
  "Danemark"=> [
    "Danemark central",
    "Danemark du Nord",
    "Danemark du Sud",
    "Jutland central",
    "Jutland du Nord",
    "Jutland du Sud",
    "la Capitale",
    "Seeland"
  ],
  "Djibouti"=> [
    "Ali Sabieh",
    "Arta",
    "Dikhil",
    "Djibouti",
    "Obock",
    "Tadjourah"
  ],
  "Dominique"=> [
    "Saint-André",
    "Saint-David",
    "Saint-George",
    "Saint-John",
    "Saint-Joseph",
    "Saint-Luke",
    "Saint-Mark",
    "Saint-Patrick",
    "Saint-Paul",
    "Saint-Peter"
  ],
  "Espagne"=> [
    "Andalousie",
    "Aragon",
    "Asturies",
    "Cantabrie",
    "Castille-et-León",
    "Castille-La Manche",
    "Catalogne",
    "Ceuta",
    "Communauté de Madrid",
    "Communauté de Valence",
    "Estrémadure",
    "Galice",
    "La Rioja",
    "Melilla",
    "Murcie",
    "Navarre",
    "Pays basque",
    "Îles Baléares",
    "Îles Canaries"
  ],
  "Estonie"=> [
    "Harju",
    "Hiiu",
    "Ida-Viru",
    "Järva",
    "Jõgeva",
    "Lääne",
    "Lääne-Viru",
    "Pärnu",
    "Põlva",
    "Rapla",
    "Saare",
    "Tartu",
    "Valga",
    "Viljandi",
    "Võru"
  ],
  "Eswatini (Swaziland)"=> [
    "Hhohho",
    "Lubombo",
    "Manzini",
    "Shiselweni"
  ],
  "Fidji"=> [
    "Ba",
    "Bua",
    "Cakaudrove",
    "Kadavu",
    "Lau",
    "Lomaiviti",
    "Macuata",
    "Nadroga-Navosa",
    "Naitasiri",
    "Namosi",
    "Ra",
    "Rewa",
    "Serua",
    "Tailevu"
  ],
  "Finlande"=> [
    "Autres parties de la Finlande",
    "Finlande propre",
    "Haut-Finlande",
    "Helsinki-Uusimaa",
    "Itä-Uusimaa",
    "Kainuu",
    "Kanta-Häme",
    "Keski-Suomi",
    "Kymenlaakso",
    "Laponie",
    "Länsi-Suomi",
    "Manner-Suomi",
    "Nord-Est",
    "Nord-Ouest",
    "Ostrobothnie",
    "Ostrobothnie du Nord",
    "Ostrobothnie du Sud",
    "Pirkanmaa",
    "Päijät-Häme",
    "Satakunta",
    "Savonie",
    "Sud-Est",
    "Sud-Ouest",
    "Tampere",
    "Uusimaa",
    "Vaasa",
    "Åland"
  ],
  "France"=> [
    "Ain",
    "Aisne",
    "Allier",
    "Alpes-de-Haute-Provence",
    "Alpes-Maritimes",
    "Ardennes",
    "Ardèche",
    "Ariège",
    "Aube",
    "Aude",
    "Aveyron",
    "Bas-Rhin",
    "Bouches-du-Rhône",
    "Calvados",
    "Cantal",
    "Charente",
    "Charente-Maritime",
    "Cher",
    "Corrèze",
    "Corse-du-Sud",
    "Creuse",
    "Côte-d'Or",
    "Côtes-d'Armor",
    "Deux-Sèvres",
    "Dordogne",
    "Doubs",
    "Drôme",
    "Essonne",
    "Eure",
    "Eure-et-Loir",
    "Finistère",
    "Gard",
    "Gers",
    "Gironde",
    "Guadeloupe",
    "Guyane",
    "Haut-Rhin",
    "Haute-Corse",
    "Haute-Garonne",
    "Haute-Loire",
    "Haute-Marne",
    "Haute-Savoie",
    "Haute-Saône",
    "Haute-Vienne",
    "Hautes-Alpes",
    "Hautes-Pyrénées",
    "Hauts-de-Seine",
    "Hérault",
    "Ille-et-Vilaine",
    "Indre",
    "Indre-et-Loire",
    "Isère",
    "Jura",
    "La Réunion",
    "Landes",
    "Loir-et-Cher",
    "Loire",
    "Loire-Atlantique",
    "Loiret",
    "Lot",
    "Lot-et-Garonne",
    "Lozère",
    "Maine-et-Loire",
    "Manche",
    "Marne",
    "Martinique",
    "Mayenne",
    "Mayotte",
    "Meurthe-et-Moselle",
    "Meuse",
    "Morbihan",
    "Moselle",
    "Nièvre",
    "Nord",
    "Oise",
    "Orne",
    "Paris",
    "Pas-de-Calais",
    "Puy-de-Dôme",
    "Pyrénées-Atlantiques",
    "Pyrénées-Orientales",
    "Rhône",
    "Sarthe",
    "Savoie",
    "Saône-et-Loire",
    "Seine-et-Marne",
    "Seine-Maritime",
    "Seine-Saint-Denis",
    "Somme",
    "Tarn",
    "Tarn-et-Garonne",
    "Territoire de Belfort",
    "Val-d'Oise",
    "Val-de-Marne",
    "Var",
    "Vaucluse",
    "Vendée",
    "Vienne",
    "Vosges",
    "Yonne",
    "Yvelines"
  ],
  "Gabon"=> [
    "Estuaire",
    "Haut-Ogooué",
    "Moyen-Ogooué",
    "Ngounié",
    "Nyanga",
    "Ogooué-Ivindo",
    "Ogooué-Lolo",
    "Ogooué-Maritime",
    "Woleu-Ntem"
  ],
  "Gambie"=> [
    "Banjul",
    "Division de Barr",
    "Division de la Rivière de l'Est",
    "Division de la Rivière de l'Ouest",
    "Division de la Rivière du Bas",
    "Division de la Rivière du Centre",
    "Division de la Rivière du Nord",
    "Kanifing"
  ],
  "Ghana"=> [
    "Ahafo",
    "Ashanti",
    "Bono",
    "Bono-Est",
    "Est",
    "Grand Accra",
    "Haut-Est",
    "Haut-Ouest",
    "Intérieur Est",
    "Intérieur Ouest",
    "Nord",
    "Nord-Est",
    "Nord-Ouest",
    "Oti",
    "Ouest",
    "Région Centrale",
    "Upper East",
    "Upper West",
    "Volta"
  ],
  "Grenade"=> [
    "Saint-André",
    "Saint-David",
    "Saint-George",
    "Saint-John",
    "Saint-Mark",
    "Saint-Patrick",
    "Saint-Paul"
  ],
  "Grèce"=> [
    "Attique",
    "Crète",
    "Est de la Macédoine et de la Thrace",
    "Macédoine centrale",
    "Macédoine occidentale",
    "Pérée Centrale de la Macédoine et de Thessalie",
    "Pérée du Dodécanèse",
    "Pérée du Péloponnèse, de l'Ouest et des Îles Ioniennes",
    "Thessalie et d'Épire",
    "Épire",
    "Îles de la mer Égée du Nord",
    "Îles de la mer Égée du Sud"
  ],
  "Guatemala"=> [
    "Alta Verapaz",
    "Baja Verapaz",
    "Chimaltenango",
    "Chiquimula",
    "El Progreso",
    "Escuintla",
    "Guatemala",
    "Huehuetenango",
    "Izabal",
    "Jalapa",
    "Jutiapa",
    "Petén",
    "Quetzaltenango",
    "Quiché",
    "Retalhuleu",
    "Sacatepéquez",
    "San Marcos",
    "Santa Rosa",
    "Sololá",
    "Suchitepéquez",
    "Totonicapán",
    "Zacapa"
  ],
  "Guinée"=> [
    "Boké",
    "Conakry",
    "Faranah",
    "Kankan",
    "Kindia",
    "Labé",
    "Mamou",
    "Nzérékoré"
  ],
  "Guinée équatoriale"=> [
    "Annobón",
    "Bioko Norte",
    "Bioko Sur",
    "Cento-Sur",
    "Kie-Ntem",
    "Littoral",
    "Wele-Nzas"
  ],
  "Guinée-Bissau"=> [
    "Bafatá",
    "Biombo",
    "Bissau",
    "Bolama",
    "Cacheu",
    "Gabú",
    "Oio",
    "Quinara",
    "Tombali"
  ],
  "Guyana"=> [
    "Barima-Waini",
    "Cuyuni-Mazaruni",
    "Demerara-Mahaica",
    "East Berbice-Corentyne",
    "Essequibo Islands-West Demerara",
    "Mahaica-Berbice",
    "Pomeroon-Supenaam",
    "Potaro-Siparuni",
    "Upper Demerara-Berbice",
    "Upper Takutu-Upper Essequibo"
  ],
  "Géorgie"=> [
    "Abkhazie",
    "Adjara",
    "Guria",
    "Imereti",
    "Kakheti",
    "Kvemo Kartli",
    "Mtskheta-Mtianeti",
    "Ratcha-Letchkhoumi et Kvemo Svaneti",
    "Samtskhe-Djavakheti",
    "Samégrelo et Zemo Svaneti",
    "Tbilissi"
  ],
  "Haïti"=> [
    "Artibonite",
    "Centre",
    "Grand'Anse",
    "Nippes",
    "Nord",
    "Nord-Est",
    "Nord-Ouest",
    "Ouest",
    "Sud",
    "Sud-Est"
  ],
  "Honduras"=> [
    "Atlantida",
    "Choluteca",
    "Colón",
    "Comayagua",
    "Copán",
    "Cortés",
    "El Paraíso",
    "Francisco Morazán",
    "Gracias a Dios",
    "Intibucá",
    "Islas de la Bahía",
    "La Paz",
    "Lempira",
    "Ocotepeque",
    "Olancho",
    "Région autonome de la Mosquitia",
    "Río Lindo",
    "Santa Bárbara",
    "Valle",
    "Yoro"
  ],
  "Hongrie"=> [
    "Baranya",
    "Borsod-Abaúj-Zemplén",
    "Budapest",
    "Bács-Kiskun",
    "Békés",
    "Csongrád-Csanád",
    "Fejér",
    "Győr-Moson-Sopron",
    "Hajdú-Bihar",
    "Heves",
    "Jász-Nagykun-Szolnok",
    "Komárom-Esztergom",
    "Nógrád",
    "Pest",
    "Somogy",
    "Szabolcs-Szatmár-Bereg",
    "Tolna",
    "Vas",
    "Veszprém",
    "Zala"
  ],
  "Inde"=> [
    "Andaman et Nicobar",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bengale occidental",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra et Nagar Haveli et Daman et Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu et Cachemire",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Pendjab",
    "Puducherry",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Tripura",
    "Télamgana",
    "Uttar Pradesh",
    "Uttarakhand"
  ],
  "Indonésie"=> [
    "Aceh",
    "Bali",
    "Bangka-Belitung",
    "Banten",
    "Bengkulu",
    "Gorontalo",
    "Irian Jaya Barat",
    "Jakarta Raya",
    "Jambi",
    "Jawa Barat",
    "Jawa Tengah",
    "Jawa Timur",
    "Kalimantan Barat",
    "Kalimantan Selatan",
    "Kalimantan Tengah",
    "Kalimantan Timur",
    "Kalimantan Utara",
    "Kepulauan Riau",
    "Lampung",
    "Maluku",
    "Maluku Utara",
    "Nusa Tenggara Barat",
    "Nusa Tenggara Timur",
    "Papua",
    "Papua Barat",
    "Riau",
    "Sulawesi Barat",
    "Sulawesi Selatan",
    "Sulawesi Tengah",
    "Sulawesi Tenggara",
    "Sulawesi Utara",
    "Sumatera Barat",
    "Sumatera Selatan",
    "Sumatera Utara",
    "Yogyakarta"
  ],
  "Irak"=> [
    "Al-Anbar",
    "Al-Başrah",
    "Al-Muthannā",
    "Al-Qādisiyyah",
    "An-Najaf",
    "Arbil",
    "As-Sulaymāniyyah",
    "Baghded",
    "Bābil",
    "Dahūk",
    "Dhi Qar",
    "Diyala",
    "Halabja",
    "Karbala'",
    "Kirkūk",
    "Maysan",
    "Nīnawá",
    "Wāsiṭ"
  ],
  "Iran"=> [
    "Ardabil",
    "Azerbaïdjan occidental",
    "Azerbaïdjan oriental",
    "Bushehr",
    "Chahar Mahal et Bakhtiari",
    "Fars",
    "Gilân",
    "Golestân",
    "Hamadân",
    "Hormozgan",
    "Ilam",
    "Isfahan",
    "Kerman",
    "Kermanshah",
    "Khorasan central",
    "Khorasan du Nord",
    "Khorasan du Sud",
    "Khuzestân",
    "Kohguilouyeh et Boyer Ahmad",
    "Kordestân",
    "Lorestan",
    "Markazi",
    "Mâzandarân",
    "Qazvin",
    "Qom",
    "Razavi Khorasan",
    "Semnan",
    "Sistan et Baloutchistan",
    "Tehran",
    "Téhran",
    "Yazd",
    "Zanjan"
  ],
  "Irlande"=> [
    "Carlow",
    "Cavan",
    "Clare",
    "Comté d'Offaly",
    "Cork",
    "Donegal",
    "Dublin",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Limerick",
    "Longford",
    "Louth",
    "Mayo",
    "Meath",
    "Monaghan",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow"
  ],
  "Islande"=> [
    "Arnarfjörður",
    "Austur-Skaftafellssýsla",
    "Austurland",
    "Borgarfjörður",
    "Dalasýsla",
    "Eyjafjörður",
    "Gullbringusýsla",
    "Hafnarfjörður",
    "Höfðahreppur",
    "Húnavatnssýsla",
    "Húnavatnssýsla austurdalur",
    "Húnavatnssýsla vesturdalur",
    "Kjalarnes",
    "Kjosar",
    "Mýrasýsla",
    "Neskaupstaður",
    "Nordurland eystra",
    "Nordurland vestra",
    "Norðurþing",
    "Reykjanes",
    "Reykjanesbær",
    "Reykjavík",
    "Skagafjörður",
    "Snæfellsbær",
    "Snæfellsnes",
    "Strandabyggd",
    "Suðurnes",
    "Suðurthing",
    "Vestfirðir",
    "Vestmannaeyjar",
    "Vesturbyggð",
    "Ísafjarðarbær"
  ],
  "Israël"=> [
    "District du Centre",
    "District du Nord",
    "District du Sud",
    "Haïfa",
    "Jérusalem",
    "Tel-Aviv"
  ],
  "Italie"=> [
    "Abruzzes",
    "Basilicate",
    "Frioul-Vénétie Julienne",
    "Latium",
    "Ligurie",
    "Lombardie",
    "Marches",
    "Molise",
    "Ombrie",
    "Piémont",
    "Pouilles",
    "Sardaigne",
    "Sicile",
    "Toscane",
    "Trentin-Haut-Adige",
    "Vallée d'Aoste",
    "Vénétie",
    "Émilie-Romagne"
  ],
  "Jamaïque"=> [
    "Clarendon",
    "Hanover",
    "Kingston",
    "Manchester",
    "Portland",
    "Saint Andrew",
    "Saint Ann",
    "Saint Catherine",
    "Saint Elizabeth",
    "Saint James",
    "Saint Mary",
    "Saint Thomas",
    "Trelawny",
    "Westmoreland"
  ],
  "Japon"=> [
    "Aichi",
    "Akita",
    "Aomori",
    "Chiba",
    "Ehime",
    "Fukui",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Gunma",
    "Hiroshima",
    "Hokkaido",
    "Hyogo",
    "Ibaraki",
    "Ishikawa",
    "Iwate",
    "Kagawa",
    "Kagoshima",
    "Kanagawa",
    "Kochi",
    "Kumamoto",
    "Kyoto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Oita",
    "Okayama",
    "Okinawa",
    "Osaka",
    "Saga",
    "Saitama",
    "Shiga",
    "Shimane",
    "Shizuoka",
    "Tochigi",
    "Tokushima",
    "Tokyo",
    "Tottori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yamanashi"
  ],
  "Jordanie"=> [
    "Ajoun",
    "Amman",
    "Aqaba",
    "Balqa",
    "Irbid",
    "Jarash",
    "Karak",
    "Ma'an",
    "Madaba",
    "Mafraq",
    "Tafilah",
    "Zarqa"
  ],
  "Kazakhstan"=> [
    "Aktobe",
    "Aktyubinsk",
    "Almaty",
    "Astana",
    "Atyrau",
    "Baïkonour",
    "Karaganda",
    "Kostanay",
    "Kyzylorda",
    "Mangystau",
    "Nord-Kazakhstan",
    "Pavlodar",
    "Petropavlovsk",
    "Semey",
    "Turpan",
    "Zhambyl",
    "Zhanaozen"
  ],
  "Kenya"=> [
    "Baringo",
    "Bomet",
    "Bungoma",
    "Busia",
    "Comté d'Embu",
    "Comté d'Isiolo",
    "Elgeyo-Marakwet",
    "Garissa",
    "Homa Bay",
    "Kajiado",
    "Kakamega",
    "Kericho",
    "Kiambu",
    "Kilifi",
    "Kirinyaga",
    "Kisii",
    "Kisumu",
    "Kitui",
    "Kwale",
    "Laikipia",
    "Lamu",
    "Machakos",
    "Makueni",
    "Mandera",
    "Marsabit",
    "Meru",
    "Migori",
    "Mombasa",
    "Murang'a",
    "Nairobi",
    "Nakuru",
    "Nandi",
    "Narok",
    "Nyamira",
    "Nyandarua",
    "Nyeri",
    "Samburu",
    "Siaya",
    "Taita-Taveta",
    "Tana River",
    "Tharaka-Nithi",
    "Trans Nzoia",
    "Turkana",
    "Uasin Gishu",
    "Vihiga",
    "Wajir",
    "West Pokot"
  ],
  "Kirghizistan"=> [
    "Batken",
    "Bichkek",
    "Chuy",
    "Issyk-Kul",
    "Jalal-Abad",
    "Naryn",
    "Och",
    "Osh",
    "Talas"
  ],
  "Kiribati"=> [
    "Banaba",
    "Groupe des îles de la Ligne",
    "Groupe des îles Gilbert",
    "Groupe des îles Phoenix"
  ],
  "Koweït"=> [
    "Al-Ahmadî",
    "Al-Asimah",
    "Al-Farwaniyah",
    "Al-Jahra",
    "Hawally",
    "Moubârak al-Kabîr"
  ],
  "Laos"=> [
    "Attapeu",
    "Bokèo",
    "Bolikhamxay",
    "Champasak",
    "Houaphanh",
    "Khammouane",
    "Louang Namtha",
    "Louang Prabang",
    "Oudômxay",
    "Phôngsaly",
    "Salavan",
    "Savannakhet",
    "Viengchan",
    "Vientiane",
    "Xaignabouli",
    "Xiangkhoang",
    "Xiasomboun",
    "Xékong"
  ],
  "Lesotho"=> [
    "Berea",
    "Butha-Buthe",
    "Leribe",
    "Mafeteng",
    "Maseru",
    "Mohales Hoek",
    "Mokhotlong",
    "Qacha's Nek",
    "Quthing",
    "Thaba-Tseka"
  ],
  "Lettonie"=> [
    "Aizkraukles novads",
    "Alūksnes novads",
    "Ape novads",
    "Auces novads",
    "Baldones novads",
    "Baltinavas novads",
    "Balvu novads",
    "Bauskas novads",
    "Beverīnas novads",
    "Brocēnu novads",
    "Burtnieku novads",
    "Carnikavas novads",
    "Cesvaines novads",
    "Ciblas novads",
    "Cēsu novads",
    "Dagdas novads",
    "Daugavpils novads",
    "Dobeles novads",
    "Dundagas novads",
    "Durbe novads",
    "Engures novads",
    "Garkalnes novads",
    "Grobiņas novads",
    "Gulbenes novads",
    "Iecavas novads",
    "Ikšķiles novads",
    "Ilūkstes novads",
    "Inčukalna novads",
    "Jaunjelgavas novads",
    "Jaunpiebalgas novads",
    "Jaunpils novads",
    "Jelgavas novads",
    "Jēkabpils novads",
    "Kandavas novads",
    "Kocēnu novads",
    "Kokneses novads",
    "Krimuldas novads",
    "Krustpils novads",
    "Krāslavas novads",
    "Kuldīgas novads",
    "Kārsavas novads",
    "Lielvārdes novads",
    "Limbažu novads",
    "Lubānas novads",
    "Ludzas novads",
    "Līgatnes novads",
    "Līvu novads",
    "Madonas novads",
    "Mazsalacas novads",
    "Mālpils novads",
    "Mārupes novads",
    "Mērsraga novads",
    "Naukšēnu novads",
    "Neretas novads",
    "Nīcas novads",
    "Ogres novads",
    "Olaines novads",
    "Ozolnieku novads",
    "Preiļu novads",
    "Priekules novads",
    "Priekuļu novads",
    "Pārgaujas novads",
    "Pārvienības novads",
    "Pļaviņu novads",
    "Raunas novads",
    "Riebiņu novads",
    "Ropažu novads",
    "Rubenis novads",
    "Rugāju novads",
    "Rundāles novads",
    "Rēzeknes novads",
    "Rūjienas novads",
    "Salaspils novads",
    "Saldus novads",
    "Saulkrastu novads",
    "Siguldas novads",
    "Skrundas novads",
    "Skrīveru novads",
    "Smiltenes novads",
    "Strenču novads",
    "Sublatas novads",
    "Sāmieru novads",
    "Sējas novads",
    "Talsu novads",
    "Tērvetes novads",
    "Vaiņodes novads",
    "Valkas novads",
    "Varakļānu novads",
    "Vecpiebalgas novads",
    "Vecumnieku novads",
    "Ventspils novads",
    "Viesītes novads",
    "Viļakas novads",
    "Viļānu novads",
    "Vārkavas novads",
    "Zilupes novads",
    "Ādažu novads",
    "Ērgļu novads",
    "Ķeguma novads",
    "Ķekavas novads"
  ],
  "Liban"=> [
    "Akkar",
    "Baalbeck-Hermel",
    "Béqaa",
    "Gouvernorat du Liban-Nord",
    "Gouvernorat du Liban-Sud",
    "Gouvernorat du Mont-Liban",
    "Nabatié"
  ],
  "Liberia"=> [
    "Bomi",
    "Bong",
    "Gbarpolu",
    "Grand Bassa",
    "Grand Cape Mount",
    "Grand Gedeh",
    "Grand Kru",
    "Lofa",
    "Margibi",
    "Maryland",
    "Montserrado",
    "Nimba",
    "River Gee",
    "Rivercess",
    "Sinoe"
  ],
  "Libye"=> [
    "Ajdabiya",
    "Al Aziziyah",
    "Al Jufrah",
    "Al Khums",
    "Al Kufrah",
    "Benghazi",
    "Darnah",
    "Ghadames",
    "Gharyan",
    "Misrata",
    "Murzuq",
    "Nalut",
    "Sabratha",
    "Sebha",
    "Sirte",
    "Tarabulus-Garb",
    "Tarhuna-Masallatah",
    "Tripoli",
    "Wadi al Hayaa",
    "Wadi al Shati"
  ],
  "Liechtenstein"=> [
    "Balzers",
    "Eschen",
    "Gamprin",
    "Mauren",
    "Planken",
    "Ruggell",
    "Schaan",
    "Schellenberg",
    "Triesen",
    "Triesenberg",
    "Vaduz"
  ],
  "Lituanie"=> [
    "Comté d'Alytus",
    "Kaunas",
    "Klaipėda",
    "Marijampolė",
    "Panevėžys",
    "Tauragė",
    "Telšiai",
    "Utena",
    "Vilnius",
    "Šiauliai"
  ],
  "Luxembourg"=> [
    "Canton d'Esch-sur-Alzette",
    "Canton de Capellen",
    "Canton de Clervaux",
    "Canton de Diekirch",
    "Canton de Echternach",
    "Canton de Esch-sur-Alzette",
    "Canton de Grevenmacher",
    "Canton de Luxembourg",
    "Canton de Mersch",
    "Canton de Redange",
    "Canton de Remich",
    "Canton de Vianden",
    "Canton de Wiltz"
  ],
  "Macédoine du Nord"=> [
    "Aerodrom",
    "Berovo",
    "Bogdanci",
    "Bogovinje",
    "Bosilovo",
    "Brvenica",
    "Debar",
    "Delčevo",
    "Demir Hisar",
    "Demir Kapija",
    "Dojran",
    "Dolneni",
    "Gevgelija",
    "Gostivar",
    "Gradsko",
    "Ilinden",
    "Jegunovce",
    "Karbinci",
    "Kičevo",
    "Konče",
    "Kočani",
    "Kratovo",
    "Kriva Palanka",
    "Krivogaštani",
    "Kršali",
    "Kumanovo",
    "Labuništa",
    "Lipkovo",
    "Lozovo",
    "Makedonska Kamenica",
    "Makedonski Brod",
    "Mogila",
    "Negotino",
    "Ohrid",
    "Pehčevo",
    "Petrovec",
    "Plasnica",
    "Podarec",
    "Prilep",
    "Probištip",
    "Radoviš",
    "Rankovce",
    "Resen",
    "Rosoman",
    "Skopje",
    "Struga",
    "Strumica",
    "Studeničani",
    "Sveti Nikole",
    "Tearce",
    "Tetovo",
    "Valandovo",
    "Veles",
    "Veliko Tresavsko",
    "Vinica",
    "Vrapčište",
    "Zelenikovo",
    "Zrnovci",
    "Čaška",
    "Čelebinci",
    "Čentiste",
    "Čepče",
    "Česinovo-Oblesevo",
    "Čučer-Sandevo",
    "Štip",
    "Šuto Orizari",
    "Želino"
  ],
  "Madagascar"=> [
    "Alaotra-Mangoro",
    "Amoron'i Mania",
    "Analamanga",
    "Analanjirofo",
    "Androy",
    "Anosy",
    "Atsimo-Andrefana",
    "Atsimo-Atsinanana",
    "Atsinanana",
    "Betsiboka",
    "Boeny",
    "Bongolava",
    "Diana",
    "Fitovinany",
    "Haute Matsiatra",
    "Ihorombe",
    "Itasy",
    "Melaky",
    "Menabe",
    "Sava",
    "Sofia",
    "Vakinankaratra",
    "Vatovavy"
  ],
  "Malaisie"=> [
    "Johor",
    "Kedah",
    "Kelantan",
    "Kuala Lumpur",
    "Labuan",
    "Malacca",
    "Negeri Sembilan",
    "Pahang",
    "Penang",
    "Perak",
    "Perlis",
    "Putrajaya",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu"
  ],
  "Malawi"=> [
    "Nord",
    "Région centrale",
    "Sud"
  ],
  "Maldives"=> [
    "Alif Alif Atoll",
    "Alif Dhaal Atoll",
    "Baa Atoll",
    "Dhaalu Atoll",
    "Faafu Atoll",
    "Gaafu Alif Atoll",
    "Gaafu Dhaal Atoll",
    "Gnaviyani Atoll",
    "Haa Alif Atoll",
    "Haa Dhaal Atoll",
    "Kaafu Atoll",
    "Laamu Atoll",
    "Lhaviyani Atoll",
    "Maale",
    "Meemu Atoll",
    "Noonu Atoll",
    "Raa Atoll",
    "Seenu Atoll",
    "Shaviyani Atoll",
    "Thaa Atoll",
    "Vaavu Atoll"
  ],
  "Mali"=> [
    "Bamako",
    "Gao",
    "Kayes",
    "Kidal",
    "Koulikoro",
    "Mopti",
    "Ménaka",
    "Sikasso",
    "Ségou",
    "Taoudénit",
    "Tombouctou"
  ],
  "Malte"=> [
    "Attard",
    "Balzan",
    "Birgu",
    "Birkirkara",
    "Bormla",
    "Dingli",
    "Fgura",
    "Floriana",
    "Fontana",
    "Ghajnsielem",
    "Gharb",
    "Gharghur",
    "Ghasri",
    "Ghaxaq",
    "Gżira",
    "Iklin",
    "Jebel",
    "Kalkara",
    "Lija",
    "Luqa",
    "Marsa",
    "Marsaskala",
    "Marsaxlokk",
    "Mdina",
    "Mellieħa",
    "Most",
    "Mqabba",
    "Msida",
    "Mtarfa",
    "Munxar",
    "Nadur",
    "Naxxar",
    "Paola",
    "Pembroke",
    "Pietà",
    "Qala",
    "Qormi",
    "Qrendi",
    "Rabat (Gozo)",
    "Rabat (Malte)",
    "Safi",
    "Saint John",
    "Saint Julian",
    "Saint Lucia",
    "Saint Paul's Bay",
    "San Ġwann",
    "Sannat",
    "Santa Venera",
    "Senglea",
    "Siggiewi",
    "Siġġiewi",
    "Sliema",
    "Swieqi",
    "Ta' Xbiex",
    "Tarxien",
    "Valletta",
    "Xaghra",
    "Xewkija",
    "Xgħajra",
    "Ħal Balzan",
    "Ħal Għargħur",
    "Ħal Safi",
    "Ħamrun",
    "Żabbar",
    "Żebbuġ (Gozo)",
    "Żebbuġ (Malte)",
    "Żejtun",
    "Żurrieq"
  ],
  "Maroc"=> [
    "Béni Mellal-Khénifra",
    "Casablanca-Settat",
    "Dakhla-Oued Eddahab",
    "Drâa-Tafilalet",
    "Fès-Meknès",
    "Guelmim-Oued Noun",
    "Laâyoune-Sakia El Hamra",
    "Marrakech-Safi",
    "Oriental",
    "Rabat-Salé-Kénitra",
    "Souss-Massa",
    "Tanger-Tétouan-Al Hoceïma"
  ],
  "Maurice"=> [
    "Agalega",
    "Beau Bassin-Rose Hill",
    "Cargados Carajos",
    "Curepipe",
    "Flacq",
    "Grand Port",
    "Moka",
    "Pamplemousses",
    "Plaines Wilhems",
    "Port Louis",
    "Quatre Bornes",
    "Rivière du Rempart",
    "Rodrigues",
    "Savanne",
    "Vacoas-Phoenix"
  ],
  "Mauritanie"=> [
    "Adrar",
    "Assaba",
    "Brakna",
    "Gorgol",
    "Guidimaka",
    "Hodh Ech Chargui",
    "Hodh El Gharbi",
    "Inchiri",
    "Nouakchott-Nord",
    "Nouakchott-Ouest",
    "Nouakchott-Sud",
    "Tagant",
    "Tichitt",
    "Tiris Zemmour",
    "Trarza"
  ],
  "Mexique"=> [
    "Aguascalientes",
    "Basse-Californie",
    "Basse-Californie du Sud",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "Mexique",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas"
  ],
  "Micronésie"=> [
    "Chuuk",
    "Kosrae",
    "Pohnpei",
    "Yap"
  ],
  "Moldavie"=> [
    "Bălți",
    "Cahul",
    "Cantemir",
    "Chișinău",
    "Cimișlia",
    "Criuleni",
    "Călărași",
    "Căușeni",
    "Dondușeni",
    "Drochia",
    "Dubăsari",
    "Edineț",
    "Florești",
    "Fălești",
    "Gagauzie",
    "Glodeni",
    "Hîncești",
    "Ialoveni",
    "Leova",
    "Nisporeni",
    "Ocnița",
    "Orhei",
    "Rezina",
    "Rîșcani",
    "Soroca",
    "Strășeni",
    "Sîngerei",
    "Taraclia",
    "Telenești",
    "Ungheni",
    "Șoldănești",
    "Ștefan Vodă"
  ],
  "Monaco"=> [],
  "Mongolie"=> [
    "Arhangay",
    "Bayan-Ölgiy",
    "Bayanhongor",
    "Bulgan",
    "Darhan Uul",
    "Dornod",
    "Dornogovi",
    "Dundgovi",
    "Dzavhan",
    "Govi-Altay",
    "Govisümber",
    "Hentiy",
    "Hövsgöl",
    "Orhon",
    "Selenge",
    "Sühnbaatar",
    "Töv",
    "Ulaanbaatar",
    "Uvs",
    "Ömnögovi",
    "Övörkhangay"
  ],
  "Monténégro"=> [
    "Andrijevica",
    "Bar",
    "Berane",
    "Bijelo Polje",
    "Budva",
    "Cetinje",
    "Danilovgrad",
    "Gusinje",
    "Herceg Novi",
    "Kolašin",
    "Kotor",
    "Mojkovac",
    "Nikšić",
    "Petnica",
    "Petrovac",
    "Plav",
    "Pljevlja",
    "Plužine",
    "Podgorica",
    "Rožaje",
    "Tivat",
    "Ulcinj",
    "Šavnik",
    "Žabljak"
  ],
  "Mozambique"=> [
    "Cabo Delgado",
    "Gaza",
    "Inhambane",
    "Manica",
    "Maputo",
    "Nampula",
    "Niassa",
    "Sofala",
    "Tete",
    "Ville de Maputo"
  ],
  "Namibie"=> [
    "Caprivi",
    "Erongo",
    "Hardap",
    "Karas",
    "Kavango",
    "Khomas",
    "Kunene",
    "Ohangwena",
    "Omaheke",
    "Omusati",
    "Oshana",
    "Oshikoto",
    "Otjozondjupa"
  ],
  "Nauru"=> [],
  "Nicaragua"=> [
    "Boaco",
    "Carazo",
    "Chinandega",
    "Chontales",
    "Costa Rica",
    "Estelí",
    "Granada",
    "Jinotega",
    "León",
    "Madriz",
    "Managua",
    "Masaya",
    "Matagalpa",
    "Nueva Segovia",
    "Rivas",
    "Région autonome de la côte caraïbe nord",
    "Région autonome de la côte caraïbe sud"
  ],
  "Niger"=> [
    "Agadez",
    "Diffa",
    "Dosso",
    "Maradi",
    "Niamey",
    "Tahoua",
    "Tillabéri",
    "Zinder"
  ],
  "Nigeria"=> [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "FCT",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara"
  ],
  "Niue"=> [],
  "Norvège"=> [
    "Buskerud",
    "Comté d'Agder",
    "Comté d'Akershus",
    "Comté d'Aust-Agder",
    "Comté d'Oppland",
    "Comté d'Østfold",
    "Finnmark",
    "Hedmark",
    "Hordaland",
    "Møre og Romsdal",
    "Nordland",
    "Rogaland",
    "Sogn og Fjordane",
    "Sør-Trøndelag",
    "Telemark",
    "Troms",
    "Trøndelag",
    "Vest-Agder",
    "Vestfold"
  ],
  "Nouvelle-Zélande"=> [
    "Auckland",
    "Bay of Plenty",
    "Canterbury",
    "Chatham Islands Territory",
    "Gisborne",
    "Hawke's Bay",
    "Manawatu-Wanganui",
    "Marlborough",
    "Nelson",
    "Northland",
    "Otago",
    "Southland",
    "Taranaki",
    "Tasman",
    "Waikato",
    "Wellington",
    "West Coast"
  ],
  "Népal"=> [
    "Bagmati",
    "Gandaki",
    "Karnali",
    "Lumbini",
    "Madhesh",
    "Province n°1",
    "Sudurpashchim"
  ],
  "Oman"=> [
    "Ad Dakhiliyah",
    "Adh Dhahirah",
    "Al Batinah Nord",
    "Al Batinah Sud",
    "Al Buraimi",
    "Al Wusta",
    "Ash Sharqiyah Nord",
    "Ash Sharqiyah Sud",
    "Dhofar",
    "Mascate",
    "Musandam"
  ],
  "Ouganda"=> [
    "District d'Abim",
    "District d'Adjumani",
    "District d'Agago",
    "District d'Amolatar",
    "District d'Amuria",
    "District d'Amuru",
    "District d'Apa Itu",
    "District d'Apac",
    "District d'Arua",
    "District d'Budaka",
    "District d'Bugiri",
    "District d'Bugweri",
    "District d'Buhweju",
    "District d'Buikwe",
    "District d'Bukai",
    "District d'Bukomansimbi",
    "District d'Bukwo",
    "District d'Bulambuli",
    "District d'Bulisa",
    "District d'Bulweju",
    "District d'Bundibugyo",
    "District d'Bunyangabu",
    "District d'Bushenyi",
    "District d'Busia",
    "District d'Butaleja",
    "District d'Butambala",
    "District d'Butebo",
    "District d'Buti",
    "District d'Buvuma",
    "District d'Buyende",
    "District d'Kabale",
    "District d'Kabango",
    "District d'Kabarole",
    "District d'Kabba",
    "District d'Kaberamaido",
    "District d'Kalangala",
    "District d'Kale",
    "District d'Kalungu",
    "District d'Kamal",
    "District d'Kampala",
    "District d'Kampala Capital City",
    "District d'Kampi",
    "District d'Kamu",
    "District d'Kamuli",
    "District d'Kamwenge"
  ],
  "Pakistan"=> [
    "Azad Cachemire",
    "Baloutchistan",
    "Gilgit-Baltistan",
    "Khyber Pakhtunkhwa",
    "Pendjab",
    "Sind",
    "Territoires tribaux administrés fédéralement"
  ],
  "Palaos"=> [
    "Aimeliik",
    "Airai",
    "Angaur",
    "Hatohobei",
    "Kayangel",
    "Koror",
    "Melekeok",
    "Ngaraard",
    "Ngarchelong",
    "Ngardmau",
    "Ngatpang",
    "Ngchesar",
    "Ngeremlengui",
    "Ngiwal",
    "Peleliu",
    "Sonsorol"
  ],
  "Palestine"=> [
    "Bethléem",
    "Deir el-Balah",
    "Gaza",
    "Hébron",
    "Jénine",
    "Jéricho et de la vallée du Jourdain",
    "Jérusalem",
    "Khan Younis",
    "Naplouse",
    "Nord Gaza",
    "Qalqilya",
    "Rafah",
    "Ramallah et Al-Bireh",
    "Salfit",
    "Tubas",
    "Tulkarm"
  ],
  "Panama"=> [
    "Bocas del Toro",
    "Chiriquí",
    "Coclé",
    "Colón",
    "Darién",
    "Emberá",
    "Guna de Wargandí",
    "Guna Yala",
    "Herrera",
    "Los Santos",
    "Ngäbe-Buglé",
    "Panama",
    "Veraguas"
  ],
  "Papouasie-Nouvelle-Guinée"=> [
    "Bougainville",
    "Chimbu",
    "Est",
    "Est de la Nouvelle-Bretagne",
    "Est de Sepik",
    "Hela",
    "Jiwaka",
    "la Nouvelle-Irlande",
    "Madang",
    "Manus",
    "Milne Bay",
    "Morobe",
    "National Capital District",
    "Ouest",
    "Ouest de la Nouvelle-Bretagne",
    "Ouest de Sepik",
    "Province centrale",
    "s Hautes-Terres",
    "Sud",
    "Sud-Hautes-Terres"
  ],
  "Paraguay"=> [
    "Alto Paraguay",
    "Alto Paraná",
    "Amambay",
    "Asunción",
    "Boquerón",
    "Caaguazú",
    "Caazapá",
    "Canindeyú",
    "Central",
    "Concepción",
    "Cordillera",
    "Guairá",
    "Itapúa",
    "Misiones",
    "Paraguarí",
    "Presidente Hayes",
    "San Pedro",
    "Ñeembucú"
  ],
  "Pays-Bas"=> [
    "Aruba",
    "Brabant-Septentrional",
    "Curaçao",
    "Drenthe",
    "Flevoland",
    "Frise",
    "Groningue",
    "Gueldre",
    "Hollande-Méridionale",
    "Hollande-Septentrionale",
    "Limbourg",
    "Overijssel",
    "Sint Maarten",
    "Utrecht",
    "Zélande"
  ],
  "Philippines"=> [
    "la capitale nationale (NCR)",
    "la Cordillère administrative",
    "Région autonome du Mindanao musulman (BARMM)",
    "Région I (Ilocos)",
    "Région II (Cagayan Valley)",
    "Région III (Central Luzon)",
    "Région IV-A (Calabarzon)",
    "Région IV-B (MIMAROPA)",
    "Région IX (Zamboanga Peninsula)",
    "Région V (Bicol)",
    "Région VI (Western Visayas)",
    "Région VII (Central Visayas)",
    "Région VIII (Eastern Visayas)",
    "Région X (Northern Mindanao)",
    "Région XI (Davao)",
    "Région XII (SOCCKSARGEN)",
    "Région XIII (Caraga)"
  ],
  "Pologne"=> [
    "Voïvodie d'Opole",
    "Voïvodie de Basse-Pologne",
    "Voïvodie de Basse-Silésie",
    "Voïvodie de Coutrse",
    "Voïvodie de Grande-Pologne",
    "Voïvodie de Lublin",
    "Voïvodie de Lubusz",
    "Voïvodie de Mazovie",
    "Voïvodie de Petite-Pologne",
    "Voïvodie de Podlachie",
    "Voïvodie de Poméranie",
    "Voïvodie de Poméranie-Occidentale",
    "Voïvodie de Sainte-Croix",
    "Voïvodie de Silésie",
    "Voïvodie de Varmie-Mazurie",
    "Voïvodie de Łódź"
  ],
  "Portugal"=> [
    "Aveiro",
    "Beja",
    "Braga",
    "Bragança",
    "Castelo Branco",
    "Coimbra",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisbonne",
    "Portalegre",
    "Porto",
    "Région autonome de Madère",
    "Région autonome des Açores",
    "Santarém",
    "Setúbal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu",
    "Évora"
  ],
  "Pérou"=> [
    "Ancash",
    "Apurímac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Cusco",
    "Huancavelica",
    "Huánuco",
    "Ica",
    "Junín",
    "La Libertad",
    "Lambayeque",
    "Lima",
    "Loreto",
    "Madre de Dios",
    "Moquegua",
    "Pasco",
    "Piura",
    "Puno",
    "San Martín",
    "Tacna",
    "Tumbes",
    "Ucayali"
  ],
  "Qatar"=> [
    "Al Daayen",
    "Al Khor",
    "Al Rayyan",
    "Al Shamal",
    "Al Wakrah",
    "la capitale Doha",
    "Umm Salal"
  ],
  "Roumanie"=> [
    "Alba",
    "Arad",
    "Argeș",
    "Bacău",
    "Bihor",
    "Bistrița-Năsăud",
    "Botoșani",
    "Brașov",
    "Brăila",
    "Bucarest",
    "Buzău",
    "Caraș-Severin",
    "Cluj",
    "Constanța",
    "Covasna",
    "Călărași",
    "Dolj",
    "Dâmbovița",
    "Galați",
    "Giurgiu",
    "Gorj",
    "Harghita",
    "Hunedoara",
    "Ialomița",
    "Iași",
    "Ilfov",
    "Maramureș",
    "Mehedinți",
    "Mureș",
    "Neamț",
    "Olt",
    "Prahova",
    "Satu Mare",
    "Sibiu",
    "Suceava",
    "Sălaj",
    "Teleorman",
    "Timiș",
    "Tulcea",
    "Vaslui",
    "Vrancea",
    "Vâlcea"
  ],
  "Royaume-Uni"=> [
    "Angleterre",
    "Bath and North East Somerset",
    "Bedford",
    "Blackburn with Darwen",
    "Blackpool",
    "Bournemouth",
    "Bracknell Forest",
    "Brighton and Hove",
    "Bristol",
    "Buckinghamshire",
    "Central Bedfordshire",
    "Cheshire East",
    "Cheshire West and Chester",
    "Cornwall",
    "County Durham",
    "Darlington",
    "Derby",
    "Dorset",
    "East Riding of Yorkshire",
    "Halton",
    "Hartlepool",
    "Herefordshire",
    "Irlande du Nord",
    "Isle of Wight",
    "Kingston upon Hull",
    "Leicester",
    "Luton",
    "Medway",
    "Middlesbrough",
    "Milton Keynes",
    "North East Lincolnshire",
    "North Lincolnshire",
    "North Somerset",
    "Pays de Galles",
    "Peterborough",
    "Plymouth",
    "Poole",
    "Portsmouth",
    "Reading",
    "Redcar and Cleveland",
    "Rutland",
    "Slough",
    "South Gloucestershire",
    "Southampton",
    "Southend-on-Sea",
    "Stockton-on-Tees",
    "Stoke-on-Trent",
    "Swindon",
    "Telford and Wrekin",
    "Thurrock",
    "Torbay",
    "Warrington",
    "West Berkshire",
    "Windsor and Maidenhead",
    "Wokingham",
    "York",
    "Écosse"
  ],
  "Russie"=> [
    "Altaï",
    "Amour",
    "Astrakhan",
    "Briansk",
    "Iaroslavl",
    "Irkoutsk",
    "Kaliningrad",
    "Kalouga",
    "Kemerovo",
    "Khabarovsk",
    "Khabarovsk Krai",
    "Kirov",
    "Kostroma",
    "Kourgan",
    "Koursk",
    "Krai de Krasnoïarsk",
    "Krai de Perm",
    "Krai de Zabaïkal",
    "Krasnodar Krai",
    "Leningrad",
    "Lipetsk",
    "Mourmansk",
    "Nièvre",
    "Novgorod",
    "Novossibirsk",
    "Oblast de Magadan",
    "Oblast de Sakhaline",
    "Oblast juif",
    "Okrug autonome de Khantys-Mansis",
    "Okrug autonome de Nenets",
    "Okrug autonome de Tchoukotka",
    "Okrug autonome de Yamalo-Nenets",
    "Omsk",
    "Orenbourg",
    "Oulianovsk",
    "Penza",
    "Primorie Krai",
    "Pskov",
    "Riazan",
    "République d'Alania (Ossétie du Nord)",
    "République d'Ingouchie",
    "République d'Oudmourtie",
    "République de Bachkirie",
    "République de Bouriatie",
    "République de Kalmykie",
    "République de Karatchaïévo-Tcherkessie",
    "République de Karelie",
    "République de Komi",
    "République de l'Adyguée",
    "République de l'Altaï",
    "République de Mari El",
    "République de Mordovie",
    "République de Sakha (Yakoutie)",
    "République de Tatarstan",
    "République de Tchouvachie",
    "République de Tchétchénie",
    "République de Touva",
    "République du Daghestan",
    "République du Kabardino-Balkarie",
    "Samara",
    "Saratov",
    "Smolensk",
    "Stavropol Krai",
    "Tambov",
    "Tcheliabinsk",
    "Tomsk",
    "Toula",
    "Tumen",
    "Tver",
    "Ville de Moscou",
    "Ville de Saint-Pétersbourg",
    "Vladimir",
    "Vologda",
    "Voronej"
  ],
  "Rwanda"=> [
    "Est",
    "Nord",
    "Ouest",
    "Sud",
    "Ville de Kigali"
  ],
  "Saint-Christophe-et-Niévès"=> [
    "Saint-Anne Sandy Point",
    "Saint-George Gingerland",
    "Saint-John Figtree",
    "Saint-John's Parish",
    "Saint-Kitts",
    "Saint-Mary Cayon",
    "Saint-Paul",
    "Saint-Paul Capisterre",
    "Saint-Paul Parish",
    "Saint-Peter Basseterre",
    "Saint-Thomas Lowland",
    "Saint-Thomas Middle Island",
    "Trinity Palmetto Point"
  ],
  "Saint-Marin"=> [
    "Acquaviva",
    "Borgo Maggiore",
    "Chiesanuova",
    "Domagnano",
    "Faetano",
    "Fiorentino",
    "Montegiardino",
    "San Marino",
    "Serravalle"
  ],
  "Saint-Siège (Vatican)"=> [],
  "Saint-Vincent-et-les-Grenadines"=> [
    "Charlotte",
    "Saint Andrew",
    "Saint David",
    "Saint George",
    "Saint Patrick",
    "Saint Vincent"
  ],
  "Sainte-Lucie"=> [
    "Anse la Raye",
    "Canaries",
    "Castries",
    "Choiseul",
    "Dennery",
    "Gros Islet",
    "Laborie",
    "Micoud",
    "Soufrière",
    "Vieux-Fort"
  ],
  "Salomon (îles)"=> [
    "Capitale Honiara",
    "Choiseul",
    "Guadalcanal",
    "Géorgias du Sud",
    "Géorgias occidentales",
    "Isabel",
    "Makira-Ulawa",
    "Malaita",
    "Rennell et Bellona",
    "Temotu"
  ],
  "Salvador"=> [
    "Ahuachapán",
    "Cabañas",
    "Chalatenango",
    "Cuscatlán",
    "La Libertad",
    "La Paz",
    "La Unión",
    "Morazán",
    "San Miguel",
    "San Salvador",
    "San Vicente",
    "Santa Ana",
    "Sonsonate",
    "Usulután"
  ],
  "Samoa"=> [
    "A'ana",
    "Aiga-i-le-Tai",
    "Atua",
    "Fa'asaleleaga",
    "Gaga'emauga",
    "Gagaifomauga",
    "Palauli",
    "Satupa'itea",
    "Tuamasaga",
    "Va'a-o-Fonoti",
    "Vaisigano"
  ],
  "Sao Tomé-et-Principe"=> [
    "Cantagalo",
    "Caué",
    "District d'Îles de Príncipe",
    "Lemba",
    "Lobata",
    "Mé-Zochi",
    "Água Grande"
  ],
  "Serbie"=> [
    "Belgrade",
    "Bor",
    "Braničevo",
    "Jablanica",
    "Kolubara",
    "la Voïvodine du Sud",
    "Mačva",
    "Moravica",
    "Nišava",
    "Pem",
    "Pirot",
    "Podunavlje",
    "Pomoravlje",
    "Pčinja",
    "Rasina",
    "Raška",
    "Smederevo",
    "Srem",
    "Sud et de l'Est de la Serbie",
    "Toplica",
    "Zaječar",
    "Zlatibor",
    "Šumadija et de l'Ouest de la Serbie"
  ],
  "Seychelles"=> [
    "Anse aux Pins",
    "Anse Boileau",
    "Anse Etoile",
    "Anse Royale",
    "Au Cap",
    "Baie Lazare",
    "Baie Sainte Anne",
    "Beau Vallon",
    "Bel Air",
    "Bel Ombre",
    "Cascade",
    "Glacis",
    "Grand'Anse (Mahé)",
    "Grand'Anse (Praslin)",
    "La Digue",
    "La Riviere Anglaise",
    "Les Mamelles",
    "Mont Buxton",
    "Mont Fleuri",
    "Plaisance",
    "Pointe La Rue",
    "Port Glaud",
    "Roche Caiman",
    "Roches Noires",
    "Saint Louis",
    "Takamaka",
    "Terre Rouge",
    "Tropiques"
  ],
  "Sierra Leone"=> [
    "Province méridionale",
    "Province orientale",
    "Province septentrionale",
    "Région occidentale"
  ],
  "Singapour"=> [
    "Singapour"
  ],
  "Slovaquie"=> [
    "Banská Bystrica",
    "Bratislava",
    "Košice",
    "Nitra",
    "Prešov",
    "Trenčín",
    "Trnava",
    "Žilina"
  ],
  "Slovénie"=> [
    "Ajdovščina",
    "Ankaran",
    "Apače",
    "Avrnek",
    "Beltinci",
    "Benedikt",
    "Bistrica ob Sotli",
    "Bled",
    "Bloke",
    "Bohinj",
    "Borovnica",
    "Bovec",
    "Braslovče",
    "Brda",
    "Brežice",
    "Britof",
    "Cankova",
    "Cerknica",
    "Cerkno",
    "Cerkvenjak",
    "Destrnik",
    "Divača",
    "Dobje",
    "Dobrepolje",
    "Dobrova–Polhov Gradec",
    "Dobrovnik",
    "Dol pri Ljubljani",
    "Dolenjske Toplice",
    "Domžale",
    "Dornava",
    "Dravograd",
    "Duplek",
    "Gorenja vas–Poljane",
    "Gorica",
    "Gorje",
    "Gornja Radgona",
    "Gornji Grad",
    "Gornji Petrovci",
    "Grad",
    "Grosuplje",
    "Hajdina",
    "Hodoš",
    "Horjul",
    "Hoče–Selo",
    "Hrastnik",
    "Hrpelje–Kozina",
    "Idrija",
    "Ig",
    "Ilirska Bistrica",
    "Izola",
    "Jesenice",
    "Jezersko",
    "Juršinci",
    "Kamnik",
    "Kanal ob Soči",
    "Kidričevo",
    "Kobarid",
    "Kobilje",
    "Komen",
    "Komenda",
    "Koper",
    "Kosijerina",
    "Kostel",
    "Kozje",
    "Kočevje",
    "Krajev",
    "Križevci",
    "Krško",
    "Kungota",
    "Kupljenik",
    "Kuzma",
    "Lendava",
    "Litija",
    "Ljutomer",
    "Logatec",
    "Lovrenc na Pohorju",
    "Loški Potok",
    "Luce",
    "Lukovica",
    "Luče",
    "Makole",
    "Markovci",
    "Medvode",
    "Menges",
    "Metlika",
    "Mežica",
    "Miklavž na Dravskem polju",
    "Miren–Kostanjevica",
    "Mirna Peč",
    "Mislinja",
    "Moravske Toplice",
    "Moravče",
    "Mozirje",
    "Muta",
    "Naklo",
    "Nazarje",
    "Nova Gorica",
    "Nova Mest",
    "Novo Mesto",
    "Odranci",
    "Oplotnica",
    "Ormož",
    "Ortnek",
    "Osilnica",
    "Pesnica",
    "Piran",
    "Pivka",
    "Podlehnik",
    "Podvelka",
    "Podčetrtek",
    "Poljčane",
    "Polzela",
    "Postojna",
    "Prebold",
    "Preddvor",
    "Prevalje",
    "Preveza",
    "Ptuj",
    "Puconci",
    "Race",
    "Radenci",
    "Radeče",
    "Radlje ob Dravi",
    "Radovljica",
    "Ravne na Koroskem",
    "Recica ob Savinji",
    "Renče–Vogrsko",
    "Ribnica",
    "Ribnica na Pohorju",
    "Rogatec",
    "Rogaška Slatina",
    "Rogašovci",
    "Rojtina",
    "Rozno",
    "Ruše",
    "Selnica ob Dravi",
    "Semič",
    "Sempeter–Vrtojba",
    "Sevnica",
    "Sežana",
    "Snežnik",
    "Sodražica",
    "Solčava",
    "Sostro",
    "Sočnik",
    "Starse",
    "Straža",
    "Sveta Ana",
    "Sveta Andra",
    "Sveta Trojica v Slovenskih Goricah",
    "Sveti Andraž v Slovenskih Goricah",
    "Sveti Jurij",
    "Sveti Jurij v Slovenskih Goricah",
    "Sveti Martin",
    "Sveti Tomaz",
    "Tabor",
    "Tišina",
    "Tolmin",
    "Trbovlje",
    "Trebnje",
    "Trnovska vas",
    "Trzic",
    "Trzin",
    "Turnišče",
    "Velika Polana",
    "Velike Lašce",
    "Veržej",
    "Videm",
    "Vitanje",
    "Vodice",
    "Vojnik",
    "Vransko",
    "Vrhnika",
    "Vuzenica",
    "Zagorje ob Savi",
    "Zavrč",
    "Zreče",
    "Črenšovci",
    "Črna na Koroskem",
    "Črnomelj",
    "Šalovci",
    "Šampion",
    "Šentilj",
    "Šentjernej",
    "Šentjur",
    "Škocjan",
    "Škofja Loka",
    "Škofljica",
    "Šmarje pri Jelšah",
    "Šmartno ob Paki",
    "Šmartno pri Litiji"
  ],
  "Somalie"=> [
    "Awdal",
    "Bakool",
    "Banaadir",
    "Bay",
    "Galguduud",
    "Gedo",
    "Hiiraan",
    "Jubbada Dhexe",
    "Jubbada Hoose",
    "Mudug",
    "Nugaal",
    "Sanaag",
    "Shabeellaha Dhexe",
    "Shabeellaha Hoose",
    "Sool",
    "Togdheer",
    "Woqooyi Galbeed"
  ],
  "Soudan"=> [
    "Darfour",
    "Est",
    "Khartoum",
    "Kordofan",
    "Kordofan-Ouest",
    "Kordofan-Sud",
    "Nil",
    "Nil Bleu",
    "Nil supérieur",
    "Nord",
    "Région centrale"
  ],
  "Soudan du Sud"=> [
    "Nil",
    "Zone de l'Abyei",
    "Équateur",
    "État d'Upper Nile",
    "État de Bahr el Ghazal du Nord",
    "État de Bahr el Ghazal du Sud",
    "État de Bahr el Ghazal occidental",
    "État de Jonglei",
    "État de l'Unité",
    "État de l'Équateur",
    "État de l'Île de Rujal",
    "État du Haut-Nil",
    "État du Lac"
  ],
  "Sri Lanka"=> [
    "Est",
    "Nord",
    "Nord-Central",
    "Nord-Ouest",
    "Ouest",
    "Province centrale",
    "Sabaragamuwa",
    "Sud",
    "Uva"
  ],
  "Suisse"=> [
    "Appenzell Rhodes-Extérieures",
    "Appenzell Rhodes-Intérieures",
    "Argovie",
    "Berne",
    "Bâle-Campagne",
    "Bâle-Ville",
    "Fribourg",
    "Genève",
    "Glaris",
    "Grisons",
    "Jura",
    "Lucerne",
    "Neuchâtel",
    "Nidwald",
    "Obwald",
    "Saint-Gall",
    "Schaffhouse",
    "Schwyz",
    "Soleure",
    "Tessin",
    "Thurgovie",
    "Uri",
    "Valais",
    "Vaud",
    "Zoug",
    "Zurich"
  ],
  "Suriname"=> [
    "Brokopondo",
    "Commewijne",
    "Coronie",
    "Marowijne",
    "Nickerie",
    "Para",
    "Paramaribo",
    "Saramacca",
    "Sipaliwini",
    "Wanica"
  ],
  "Suède"=> [
    "Blekinge",
    "Comté d'Örebro",
    "Comté d'Östergötland",
    "Dalécarlie",
    "Gotland",
    "Gävleborg",
    "Halland",
    "Jämtland",
    "Jönköping",
    "Kalmar",
    "Kronoberg",
    "Norrbotten",
    "Skåne",
    "Stockholm",
    "Södermanland",
    "Uppsala",
    "Värmland",
    "Västerbotten",
    "Västernorrland",
    "Västmanland",
    "Västra Götaland"
  ],
  "Syrie"=> [
    "Alep",
    "Damas",
    "Deir ez-Zor",
    "Hama",
    "Hassaké",
    "Homs",
    "Idlib",
    "Lattaquié",
    "Qouneïtra",
    "Raqqa",
    "Rif Dimashq",
    "Soueïda",
    "Tartous"
  ],
  "Sénégal"=> [
    "Dakar",
    "Diourbel",
    "Fatick",
    "Kaffrine",
    "Kaolack",
    "Kolda",
    "Koumpentoum",
    "Kédougou",
    "Louga",
    "Matam",
    "Nioro du Rip",
    "Podor",
    "Saint-Louis",
    "Sédhiou",
    "Tambacounda",
    "Thiès",
    "Vélingara",
    "Ziguinchor"
  ],
  "Tadjikistan"=> [
    "Khatlon",
    "Région autonome du Haut-Badakhshan",
    "république subordination",
    "Sughd"
  ],
  "Tanzanie"=> [
    "Arusha",
    "Dar es Salaam",
    "Dodoma",
    "Geita",
    "Iringa",
    "Kagera",
    "Kaskazini Pemba",
    "Kaskazini Unguja",
    "Katavi",
    "Kigoma",
    "Kilimanjaro",
    "Kusini Pemba",
    "Kusini Unguja",
    "Lindi",
    "Manyara",
    "Mara",
    "Mbeya",
    "Mjini Magharibi",
    "Morogoro",
    "Mtwara",
    "Mwanza",
    "Njombe",
    "Pwani",
    "Rukwa",
    "Ruvuma",
    "Shinyanga",
    "Simiyu",
    "Singida",
    "Tabora",
    "Tanga"
  ],
  "Tchad"=> [
    "Bahr el Ghazal",
    "Barh el Gazel",
    "Batha",
    "Borkou",
    "Chari-Baguirmi",
    "Ennedi Est",
    "Ennedi Ouest",
    "Guéra",
    "Hadjer-Lamis",
    "Kanem",
    "Lac",
    "Logone Occidental",
    "Logone Oriental",
    "Mandoul",
    "Mayo-Kebbi Est",
    "Mayo-Kebbi Ouest",
    "Moyen-Chari",
    "N'Djamena",
    "Ouaddaï",
    "Salamat",
    "Sila",
    "Tandjilé",
    "Tibesti",
    "Toubou",
    "Wadi Fira"
  ],
  "Tchéquie"=> [
    "Brno",
    "Bruntál",
    "Cheb",
    "Chomutov",
    "Domažlice",
    "Děčín",
    "Frýdek-Místek",
    "Hradec Králové",
    "Jeseník",
    "Jihlava",
    "Jindřichův Hradec",
    "Karlovy Vary",
    "Karviná",
    "Klatovy",
    "Kroměříž",
    "Královéhradecký",
    "Liberec",
    "Most",
    "Nový Jičín",
    "Olomouc",
    "Ostrava",
    "Pardubice",
    "Pelhřimov",
    "Plzeň",
    "Prachatice",
    "Písek",
    "Přerov",
    "Rokycany",
    "Sokolov",
    "Strakonice",
    "Tachov",
    "Teplice",
    "Tábor",
    "Třebíč",
    "Vsetín",
    "Vysočina",
    "Ústí nad Labem",
    "Český Krumlov",
    "Šumperk",
    "Žďár nad Sázavou"
  ],
  "Thaïlande"=> [
    "Amnat Charoen",
    "Ang Thong",
    "Bueng Kan",
    "Buri Ram",
    "Chachoengsao",
    "Chai Nat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chonburi",
    "Chumphon",
    "Kalasin",
    "Kamphaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Krung Thep Maha Nakhon",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lopburi",
    "Mae Hong Son",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Nan",
    "Narathiwat",
    "Nong Bua Lamphu",
    "Nong Khai",
    "Nonthaburi",
    "Pathum Thani",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phra Nakhon Si Ayutthaya",
    "Phrae",
    "Phuket",
    "Prachinburi",
    "Prachuap Khiri Khan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Roi Et",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Saraburi",
    "Satun",
    "Sing Buri",
    "Sisaket",
    "Songkhla",
    "Sukhothai",
    "Suphan Buri",
    "Surat Thani",
    "Surin",
    "Tak",
    "Trang",
    "Trat",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasothon"
  ],
  "Timor oriental"=> [
    "Aileu",
    "Ainaro",
    "Baucau",
    "Bobonaro",
    "Cova Lima",
    "Dili",
    "Ermera",
    "Lautém",
    "Liquiça",
    "Manatuto",
    "Manufahi",
    "Oecusse",
    "Viqueque"
  ],
  "Togo"=> [
    "la Kara",
    "la Maritime",
    "Région centrale",
    "s Plateaux",
    "s Savanes"
  ],
  "Tonga"=> [
    "Divisions de 'Eua",
    "Divisions de Ha'apai",
    "Divisions de Tongatapu",
    "Divisions de Vava'u"
  ],
  "Trinité-et-Tobago"=> [
    "Arima",
    "Chaguanas",
    "Couva-Tabaquite-Talparo",
    "Diego Martin",
    "Eastern Tobago",
    "Penal-Debe",
    "Point Fortin",
    "Princes Town",
    "Rio Claro-Mayaro",
    "San Fernando",
    "San Juan-Laventille",
    "Sangre Grande",
    "Siparia",
    "Tunapuna-Piarco"
  ],
  "Tunisie"=> [
    "Ariana",
    "Ben Arous",
    "Bizerte",
    "Béja",
    "Gabès",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kebili",
    "Kef",
    "Kébili",
    "Mahdia",
    "Manouba",
    "Monastir",
    "Médenine",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan"
  ],
  "Turkménistan"=> [
    "Ahal",
    "Balkan",
    "Daşoguz",
    "Lebap",
    "Mary"
  ],
  "Turquie"=> [
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Aksaray",
    "Ankara",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydın",
    "Ağrı",
    "Balıkesir",
    "Bartın",
    "Batman",
    "Bayburt",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Denizli",
    "Diyarbakır",
    "Edirne",
    "Elâzığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Hatay",
    "Isparta",
    "Iğdır",
    "İstanbul",
    "İzmir",
    "Kahramanmaraş",
    "Karabük",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Kırklareli",
    "Kırıkkale",
    "Kırşehir",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mersin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Sakarya",
    "Samsun",
    "Siirt",
    "Sinop",
    "Sivas",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Uşak",
    "Van",
    "Yalova",
    "Yozgat",
    "Zonguldak",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Şanlıurfa",
    "Şırnak"
  ],
  "Tuvalu"=> [
    "Funafuti",
    "Nanumanga",
    "Nanumea",
    "Niutao",
    "Nui",
    "Nukufetau",
    "Nukulaelae",
    "Vaaitupu"
  ],
  "Ukraine"=> [
    "Dnipropetrovsk",
    "Donetsk",
    "Ivano-Frankivsk",
    "Joum",
    "Kharkiv",
    "Kherson",
    "Khmelnytskyï",
    "Kiev",
    "Kirovohrad",
    "Louhansk",
    "Lviv",
    "Mykolaïv",
    "Odessa",
    "Poltava",
    "Rivne",
    "Soumy",
    "Tcherkasy",
    "Tchernihiv",
    "Tchernivtsi",
    "Ternopil",
    "Vinnytsia",
    "Volhynie",
    "Zakarpattia",
    "Zaporijjia"
  ],
  "Uruguay"=> [
    "Artigas",
    "Canelones",
    "Cerro Largo",
    "Colonia",
    "Durazno",
    "Flores",
    "Florida",
    "Lavalleja",
    "Maldonado",
    "Montevideo",
    "Paysandú",
    "Rivera",
    "Rocha",
    "Río Negro",
    "Salto",
    "San José",
    "Soriano",
    "Tacuarembó",
    "Treinta y Tres"
  ],
  "Vanuatu"=> [
    "Malampa",
    "Pénama",
    "Sanma",
    "Shéfa",
    "Taféa",
    "Torba"
  ],
  "Venezuela"=> [
    "Amazonas",
    "Anzoátegui",
    "Apure",
    "Aragua",
    "Barinas",
    "Bolívar",
    "Carabobo",
    "Cojedes",
    "Delta Amacuro",
    "Falcón",
    "Guárico",
    "Lara",
    "Miranda",
    "Monagas",
    "Mérida",
    "Nueva Esparta",
    "Portuguesa",
    "Sucre",
    "Territoires fédéraux",
    "Trujillo",
    "Táchira",
    "Vargas",
    "Yaracuy",
    "Zulia"
  ],
  "Viêt Nam"=> [
    "An Giang",
    "Bà Rịa-Vũng Tàu",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Bình Định",
    "Bạc Liêu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bắc Ninh",
    "Bến Tre",
    "Cao Bằng",
    "Cà Mau",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Tĩnh",
    "Hòa Bình",
    "Hưng Yên",
    "Hải Dương",
    "Hậu Giang",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Long An",
    "Lào Cai",
    "Lâm Đồng",
    "Lạng Sơn",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Thanh Hóa",
    "Thái Bình",
    "Thái Nguyên",
    "Thừa Thiên-Huế",
    "Tiền Giang",
    "Tuyên Quang",
    "Tây Ninh",
    "Ville de Cần Thơ",
    "Ville de Hanoï",
    "Ville de Huế",
    "Ville de Hải Phòng",
    "Ville de Hồ Chí Minh",
    "Ville de Đà Nẵng",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
    "Điện Biên",
    "Đắk Lắk",
    "Đắk Nông",
    "Đồng Nai",
    "Đồng Tháp"
  ],
  "Yémen"=> [
    "Abian",
    "Abyan",
    "Aden",
    "Al Bayda",
    "Al Hudaydah",
    "Al Jawf",
    "Al Mahrah",
    "Al Mahwit",
    "Aman",
    "Amran",
    "Dhala",
    "Dhamar",
    "Hajjah",
    "Hodeïda",
    "Ibb",
    "Lahej",
    "Marib",
    "Raymah",
    "Saada",
    "Sanaa",
    "Shabwah",
    "Socotra",
    "Taïz"
  ],
  "Zambie"=> [
    "Copperbelt",
    "Luapula",
    "Lusaka",
    "Nord",
    "Nord-Ouest",
    "Province centrale",
    "Province méridionale",
    "Province occidentale",
    "Province orientale",
    "Province septentrionale"
  ],
  "Zimbabwe"=> [
    "Bulawayo",
    "Harare",
    "Manicaland",
    "Mashonaland central",
    "Mashonaland occidental",
    "Mashonaland oriental",
    "Masvingo",
    "Matabeleland du Nord",
    "Matabeleland du Sud",
    "Midlands"
  ],
  "Égypte"=> [
    "Ad Daqahliyah",
    "Al Bahr al Ahmar",
    "Al Buhayrah",
    "Al Fayyum",
    "Al Gharbiyah",
    "Al Iskandariyah",
    "Al Isma'iliyah",
    "Al Jizah",
    "Al Minufiyah",
    "Al Minya",
    "Al Qahirah",
    "Al Qalyubiyah",
    "Al Wadi al Jadid",
    "As Suways",
    "Ash Sharqiyah",
    "Aswan",
    "Asyut",
    "Bani Suwayf",
    "Bur Sa'id",
    "Dumyat",
    "Janub Sina'",
    "Kafr ash Shaykh",
    "Matruh",
    "Qina",
    "Shamal Sina'",
    "Suhaj"
  ],
  "Émirats arabes unis"=> [
    "Emirat d'Abou Dabi",
    "Emirat d'Ajman",
    "Emirat d'Um al-Qaiwain",
    "Emirat de Dubaï",
    "Emirat de Fujaïrah",
    "Emirat de Ras al-Khaimah",
    "Emirat de Sharjah"
  ],
  "Équateur"=> [
    "Azuay",
    "Bolívar",
    "Carchi",
    "Cañar",
    "Chimborazo",
    "Cotopaxi",
    "El Oro",
    "Esmeraldas",
    "Galápagos",
    "Guayas",
    "Imbabura",
    "Loja",
    "Los Ríos",
    "Manabí",
    "Morona-Santiago",
    "Napo",
    "Orellana",
    "Pastaza",
    "Pichincha",
    "Santa Elena",
    "Santo Domingo de los Tsáchilas",
    "Sucumbíos",
    "Tungurahua",
    "Zamora-Chinchipe"
  ],
  "Érythrée"=> [
    "Anseba",
    "Debub",
    "Gash-Barka",
    "Maekel",
    "Semenawi Keyih Bahri"
  ],
  "États-Unis"=> [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "Californie",
    "Caroline du Nord",
    "Caroline du Sud",
    "Colorado",
    "Columbia",
    "Connecticut",
    "Dakota du Nord",
    "Dakota du Sud",
    "Delaware",
    "Floride",
    "Géorgie",
    "Hawaï",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiane",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New York",
    "Nouveau-Mexique",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvanie",
    "Rhode Island",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginie",
    "Virginie-Occidentale",
    "Washington",
    "Wisconsin",
    "Wyoming"
  ],
  "Éthiopie"=> [
    "Addis-Abeba",
    "Afar",
    "Amhara",
    "Benishangul-Gumuz",
    "Direction",
    "Gambela",
    "Harari",
    "Oromia",
    "s nations, nationalités et peuples du Sud",
    "Sidama",
    "Somali",
    "Tigré"
  ],
  "Îles Cook"=> [
    "Aitutaki",
    "Atiu",
    "Mangaia",
    "Manihiki",
    "Manuae",
    "Mauke",
    "Mitiaro",
    "Palmerston",
    "Pukapuka",
    "Rakahanga",
    "Rarotonga",
    "Suwarrow",
    "Takutea"
  ],
  "Îles Marshall"=> [
    "Ailinglaplap",
    "Ailuk",
    "Arno",
    "Aur",
    "Bikini",
    "Bikini Nord",
    "Bikini Sud",
    "Ebon",
    "Enewetak",
    "Erikub",
    "Jabat",
    "Jaluit",
    "Jemo",
    "Kili",
    "Kwajalein",
    "Lae",
    "Lib",
    "Likiep",
    "Majuro",
    "Maloelap",
    "Mejit",
    "Mili",
    "Namorik",
    "Namu",
    "Rongelap",
    "Rongrik",
    "Taka",
    "Tinak",
    "Ujae",
    "Ujelang",
    "Utirik",
    "Wotho",
    "Wotje"
  ],
  "Îles Salomon"=> [
    "Capitale Honiara",
    "Choiseul",
    "Guadalcanal",
    "Géorgias du Sud",
    "Géorgias occidentales",
    "Isabel",
    "Makira-Ulawa",
    "Malaita",
    "Rennell et Bellona",
    "Temotu"
  ]
]
?>