CREATE TABLE IF NOT EXISTS season_duration (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    annee SMALLINT UNSIGNED NOT NULL,
    winter TINYINT UNSIGNED NOT NULL DEFAULT 13,
    spring TINYINT UNSIGNED NOT NULL DEFAULT 13,
    summer TINYINT UNSIGNED NOT NULL DEFAULT 13,
    fall TINYINT UNSIGNED NOT NULL DEFAULT 13,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uq_season_duration_annee (annee)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
